version: '3.8'

services:
  auth-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "5432:5432"
    volumes: [ auth-db-data:/var/lib/postgresql/data ]
    networks: [ marketplace-network ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./apps/auth-service
      dockerfile: Dockerfile
    env_file: [./apps/auth-service/.env.development]
    init: true
    ports:
      - "3001:3000"
    depends_on:
      auth-db:
        condition: service_started
    networks: [ marketplace-network ]
    restart: unless-stopped

#  order-db:
#    image: postgres:16-alpine
#    container_name: order-db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: order_db
#    ports:
#      - "5433:5432"
#    volumes:
#      - order-db-data:/var/lib/postgresql/data
#    networks:
#      - marketplace-network
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  seller-db:
#    image: postgres:16-alpine
#    container_name: seller-db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: seller_db
#    ports:
#      - "5434:5432"
#    volumes:
#      - seller-db-data:/var/lib/postgresql/data
#    networks:
#      - marketplace-network
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  rabbitmq:
#    image: rabbitmq:3.12-management-alpine
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq
#    networks:
#      - marketplace-network
#    healthcheck:
#      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

volumes:
  auth-db-data:
  order-db-data:
  seller-db-data:
  rabbitmq-data:

networks:
  marketplace-network:
    driver: bridge

