FROM node:24-slim

RUN apt update && apt install -y curl
WORKDIR /app
RUN npm i -g corepack
RUN corepack enable
COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store pnpm fetch --frozen-lockfile
RUN --mount=type=cache,id=pnpm,target=/root/.local/share/pnpm/store pnpm install --frozen-lockfile

COPY . .
ENTRYPOINT ["pnpm", "start"]
