name: Deploy to GCE
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1022630044535/locations/global/workloadIdentityPools/github/providers/github
          service_account: github-deployer@market-place-489716.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
      - name: Docker Auth
        run: |-
          gcloud auth configure-docker europe-west10-docker.pkg.dev
      - name: Build and Push Container
        working-directory: apps/auth-service
        run: |-
          docker build -t europe-west10-docker.pkg.dev/market-place-489716/monorepo/auth-service:${{ github.sha }} .
          docker push europe-west10-docker.pkg.dev/market-place-489716/monorepo/auth-service:${{ github.sha }}
      - name: Deploy to GCE
        run: |-
          gcloud compute ssh auth-service \
            --zone="europe-west10-c" \
            --project="market-place-489716" \
            --command="
              gcloud auth configure-docker europe-west10-docker.pkg.dev --quiet
          
              docker pull europe-west10-docker.pkg.dev/market-place-489716/monorepo/auth-service:${{ github.sha }}
          
              docker stop auth-service || true
              docker rm auth-service || true
              docker run -d --name auth-service -p 3000:3000 europe-west10-docker.pkg.dev/market-place-489716/monorepo/auth-service:${{ github.sha }}
            "
