name: Unit Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - auth-service
          - seller-service
          - order-service
          - frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: apps/${{ matrix.service }}/pnpm-lock.yaml

      - name: Install Dependencies
        working-directory: apps/${{ matrix.service }}
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        working-directory: apps/${{ matrix.service }}
        run: pnpm test
